#! /usr/bin/env bash

local_version=$(go version | awk '{print $3}' | tr -d '\n')
# Get latest version from Go site
raw_latest=$(curl -s https://go.dev/VERSION?m=text)
# Extract only the version number (go1.25.0)
latest_version=$(echo "$raw_latest" | grep -oE 'go[0-9]+\.[0-9]+(\.[0-9]+)?')

echo "Local: $local_version"
echo "Latest: $latest_version"

if [ "$local_version" = "$latest_version" ]; then
    echo "✅ You are up to date: $local_version"
else
    echo "⚠️ A new Go version is available: $latest_version (you have $local_version)"
    echo "Upgrading..."

    #Construct filename
    file_name="${latest_version}.linux-amd64.tar.gz"
    # Download tarball
    wget "https://dl.google.com/go/${file_name}"
    # Verify checksum
    wget "https://dl.google.com/go/${file_name}.sha256"
    shasum -c "${file_name}.sha256"
    # Remove old installation of go
    sudo rm -rf /usr/local/go
    # Install new Go
    sudo tar -C /usr/local -xzf "${file_name}"

    echo "🎉 Upgraded Go version to: $latest_version"
fi

